// Credit @HomelessLemon and @Violents

//@version=4

study("Renko Scalping Idea", shorttitle="Renko Scalping Idea", overlay=true)

iRed = 0
iGreen = 0

c1 = color.new(#26a69a, 25)
c2 = color.new(#ef5350, 25)

cGreen1 = color.new(#d1fa02, 25)
cGreen2 = color.new(#b0fa02, 25)
cGreen3 = color.new(#82fa02, 25)
cGreen4 = color.new(#17fa02, 25)

cYellow = color.new(#baa100, 25)

cRed1 = color.new(#fa7a02, 25)
cRed2 = color.new(#fa4d02, 25)
cRed3 = color.new(#fa2c02, 25)
cRed4 = color.new(#fa0202, 25)

count = 1 * 5
maNumber = 16

getMa(c)=>
    l = count + (1 * c)
    sma(close, l)

sma6 =  maNumber >= 6  ? getMa(5 ) : na
sma7 =  maNumber >= 7  ? getMa(6 ) : na
sma8 =  maNumber >= 8  ? getMa(7 ) : na
sma9 =  maNumber >= 9  ? getMa(8 ) : na
sma10 = maNumber >= 10 ? getMa(9 ) : na
sma11 = maNumber >= 11 ? getMa(10) : na
sma12 = maNumber >= 12 ? getMa(11) : na
sma13 = maNumber >= 13 ? getMa(12) : na
sma14 = maNumber >= 14 ? getMa(13) : na
sma15 = maNumber >= 15 ? getMa(14) : na
sma16 = maNumber >= 16 ? getMa(15) : na
sma17 = maNumber >= 17 ? getMa(16) : na
sma18 = maNumber >= 18 ? getMa(17) : na
sma19 = maNumber >= 19 ? getMa(18) : na
sma20 = maNumber >= 20 ? getMa(19) : na
sma21 = maNumber >= 21 ? getMa(20) : na

if (sma6 <= close)
    iGreen := iGreen + 1 
else
    iRed := iRed + 1
if (sma7 <= close)
    iGreen := iGreen + 1 
else
    iRed := iRed + 1
if (sma8 <= close)
    iGreen := iGreen + 1 
else
    iRed := iRed + 1
if (sma9 <= close)
    iGreen := iGreen + 1 
else
    iRed := iRed + 1
if (sma10 <= close)
    iGreen := iGreen + 1 
else
    iRed := iRed + 1
if (sma11 <= close)
    iGreen := iGreen + 1 
else
    iRed := iRed + 1
if (sma12 <= close)
    iGreen := iGreen + 1 
else
    iRed := iRed + 1
if (sma13 <= close)
    iGreen := iGreen + 1 
else
    iRed := iRed + 1
if (sma14 <= close)
    iGreen := iGreen + 1 
else
    iRed := iRed + 1
if (sma15 <= close)
    iGreen := iGreen + 1 
else
    iRed := iRed + 1
if (sma16 <= close)
    iGreen := iGreen + 1 
else
    iRed := iRed + 1
if (sma17 <= close)
    iGreen := iGreen + 1 
else
    iRed := iRed + 1
if (sma18 <= close)
    iGreen := iGreen + 1 
else
    iRed := iRed + 1
if (sma19 <= close)
    iGreen := iGreen + 1 
else
    iRed := iRed + 1
if (sma20 <= close)
    iGreen := iGreen + 1 
else
    iRed := iRed + 1
if (sma21 <= close)
    iGreen := iGreen + 1 
else
    iRed := iRed + 1

if (iRed > 15)
    c1 := color.red
else if (iGreen > 15)
    c1 := color.lime
else
    c1 := color.yellow

barcolor(c1)
plot(sma6,  color=c1, title="MA21", linewidth=2, style=plot.style_line)
